CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    birth_date DATE NOT NULL,
    user_type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_cpf UNIQUE (cpf)
);

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    address VARCHAR(500) NOT NULL,
    price_per_night NUMERIC(12, 2) NOT NULL,
    type VARCHAR(30) NOT NULL,
    host_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT ck_property_price_positive CHECK (price_per_night > 0),
    CONSTRAINT ck_property_type CHECK (type IN ('HOUSE', 'APARTMENT', 'HOTEL', 'ROOM', 'CABIN', 'CHALET')),
    CONSTRAINT ck_property_status CHECK (status IN ('AVAILABLE', 'UNAVAILABLE')),
    CONSTRAINT fk_property_host FOREIGN KEY (host_id) REFERENCES users (id)
);

CREATE TABLE booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT ck_booking_dates CHECK (check_out > check_in),
    CONSTRAINT ck_booking_total_price CHECK (total_price >= 0),
    CONSTRAINT ck_booking_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_booking_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT fk_booking_guest FOREIGN KEY (guest_id) REFERENCES users (id),
    CONSTRAINT fk_booking_property FOREIGN KEY (property_id) REFERENCES property (id)
);

CREATE INDEX idx_booking_property_dates ON booking (property_id, check_in, check_out);
CREATE INDEX idx_booking_guest ON booking (guest_id);
CREATE INDEX idx_property_host ON property (host_id);
CREATE INDEX idx_property_status_type ON property (status, type);

ALTER TABLE booking
    ADD CONSTRAINT ex_booking_no_overlap
    EXCLUDE USING gist (
        property_id WITH =,
        daterange(check_in, check_out, '[)') WITH &&
    ) WHERE (status IN ('PENDING', 'CONFIRMED', 'COMPLETED'));

CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    external_id VARCHAR(255),
    idempotency_key VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_payment_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uk_payment_provider_external_id UNIQUE (provider, external_id),
    CONSTRAINT ck_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_status CHECK (status IN ('PENDING', 'PROCESSING', 'AUTHORIZED', 'PAID', 'FAILED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED')),
    CONSTRAINT ck_payment_provider CHECK (provider IN ('STRIPE', 'MERCADO_PAGO', 'PAGAR_ME')),
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES booking (id)
);

CREATE TABLE payment_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    provider_attempt_id VARCHAR(255),
    failure_code VARCHAR(100),
    failure_message VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_payment_attempt_status CHECK (status IN ('PROCESSING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT fk_payment_attempt_payment FOREIGN KEY (payment_id) REFERENCES payment (id)
);

CREATE TABLE refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    external_id VARCHAR(255),
    idempotency_key VARCHAR(100) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refund_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uk_refund_external_id UNIQUE (external_id),
    CONSTRAINT ck_refund_amount CHECK (amount > 0),
    CONSTRAINT ck_refund_status CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT fk_refund_payment FOREIGN KEY (payment_id) REFERENCES payment (id)
);

CREATE INDEX idx_payment_booking ON payment (booking_id);
CREATE INDEX idx_payment_status ON payment (status);
CREATE INDEX idx_payment_attempt_payment ON payment_attempt (payment_id);
CREATE INDEX idx_refund_payment ON refund (payment_id);
