ALTER TABLE booking
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN confirmed_at TIMESTAMPTZ,
    ADD COLUMN cancelled_at TIMESTAMPTZ,
    ADD CONSTRAINT ck_booking_confirmation_time CHECK (
        (status = 'CONFIRMED' AND confirmed_at IS NOT NULL) OR status <> 'CONFIRMED'
    ),
    ADD CONSTRAINT ck_booking_cancellation_time CHECK (
        (status = 'CANCELLED' AND cancelled_at IS NOT NULL) OR status <> 'CANCELLED'
    );

ALTER TABLE booking ALTER COLUMN created_at DROP DEFAULT;

ALTER TABLE property
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE property ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE property ALTER COLUMN updated_at DROP DEFAULT;

CREATE TABLE amenity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_amenity_name UNIQUE (name)
);

CREATE TABLE property_amenity (
    property_id BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    amenity_id BIGINT NOT NULL REFERENCES amenity (id),
    PRIMARY KEY (property_id, amenity_id)
);

CREATE TABLE property_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    url VARCHAR(2048) NOT NULL,
    alt_text VARCHAR(255),
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    CONSTRAINT uk_property_photo_position UNIQUE (property_id, display_order)
);

CREATE INDEX idx_property_photo_property ON property_photo (property_id);

CREATE TABLE daily_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    price_date DATE NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    CONSTRAINT uk_daily_price_property_date UNIQUE (property_id, price_date)
);

CREATE TABLE availability_block (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_availability_block_dates CHECK (end_date > start_date)
);

CREATE INDEX idx_availability_block_property_dates
    ON availability_block (property_id, start_date, end_date);

ALTER TABLE availability_block
    ADD CONSTRAINT ex_availability_block_no_overlap
    EXCLUDE USING gist (
        property_id WITH =,
        daterange(start_date, end_date, '[)') WITH &&
    );
